### ISSUE TITLE
Interesting stuff

### ISSUE THREAD

**Issue by asim** [nlepage/go-wasm-http-server#1]
Very cool project. I've been trying to figure out how to integrate wasm into github.com/micro/micro and I think you've given me some good ideas. Do you have an example demo running anywhere?

**Comment by nlepage** [comment]
Hi @asim thanks for your interest
You can check out the [Examples section of the README](https://github.com/nlepage/go-wasm-http-server#examples)
Tell me if you have questions.

**Comment by asim** [comment]
Thanks I'll have a look
