### ISSUE TITLE
Query

### ISSUE THREAD

**Issue by Michael-F-Ellis** [nlepage/go-wasm-http-server#3]
This looks interesting!  Just want to make sure I comprehend what it does before diving in.

Suppose I have an application that calls a  third party JS library function that expects to fetch a file from a server, say,

```
MidiJS.play(URL) // where the server at URL generates and returns a midi file to be played
```

Can I use `go-wasm-http-server` in a Go wasm app that generates the midi file content locally in the user's browser to provide a pseudo URL that returns the generated content to the JS call?

**Comment by nlepage** [comment]
Hi, thanks for your interest.

The main requirement here is that the server generating the midi file is fully implemented in Go (this also means no dependencies on C/C++ libraries) ; if it is the case then this should be possible.

**Comment by Michael-F-Ellis** [comment]
> The main requirement here is that the server generating the midi file is fully implemented in Go (this also means no dependencies on C/C++ libraries) ; if it is the case then this should be possible.

That's the case for the project I have in mind (https://github.com/Michael-F-Ellis/infinite-etudes).  I've been looking for a way to offload the computation and record-keeping to the client's browser. 

Beyond that, I see your project as a way to to facilitate using the many existing JS libs that expect to fetch from URLs.  Seems like a real contribution toward making Go WebAssembly more usable.

**Comment by nlepage** [comment]
Good! Let me know if you have any issues.

**Comment by Michael-F-Ellis** [comment]
Thanks!  Might be month or so before I get a chance to revisit that project (paid work comes before personal, alas)
