### ISSUE TITLE
Cannot use hello example

### ISSUE THREAD

**Issue by themysticsavages** [nlepage/go-wasm-http-server#6]
I have the files used in the `/docs/hello` folder.
```
api.go
index.html
sw.js
```
Using the prebuilt wasm from the folder works, but if I try to build the Go source code:
```bash
GOOS=js GOARCH=wasm go build -o api.wasm .
```
The example does not alert you.
Also, if it helps:
- I installed the go-wasm-http-server library with `go get`
- My go version is `go version go1.13.8 linux/amd64`

**Comment by nlepage** [comment]
Hi @themysticsavages 

Is there an error message?

**Comment by themysticsavages** [comment]
No, there aren't any.

**Comment by nlepage** [comment]
Not reproduced.
