### ISSUE TITLE
run go server in docker wasm container

### ISSUE THREAD

**Issue by mjcc30** [nlepage/go-wasm-http-server#8]
**Is your feature request related to a problem?**
run go server build with tiny go in docker wasm container

**Describe the solution you'd like**
Hi, i found this article about how to run wasm docker with a rust server example:
[docker-wasm-technical-preview](https://www.docker.com/blog/docker-wasm-technical-preview/)
I would like to run a go server in a wasm container so i found your package
but i can't make a wasm server with go working in a wasm container
do you know how i can do this or if it's possible ?
Thanks

step to reproduce:

first we need to install docker preview version from [documentation](https://docs.docker.com/desktop/wasm/)

main.go
```
package main

import (
	"encoding/json"
	"fmt"
	"net/http"

	wasmhttp "github.com/nlepage/go-wasm-http-server"
)

func main() {
	http.HandleFunc("/hello", func(res http.ResponseWriter, req *http.Request) {
		params := make(map[string]string)
		if err := json.NewDecoder(req.Body).Decode(&params); err != nil {
			panic(err)
		}

		res.Header().Add("Content-Type", "application/json")
		if err := json.NewEncoder(res).Encode(map[string]string{
			"message": fmt.Sprintf("Hello %s!", params["name"]),
		}); err != nil {
			panic(err)
		}
	})

	wasmhttp.Serve(nil)

	select {}
}
```

build command
```bash
tinygo build -o main.wasm -target=wasi main.go
```

Dockerfile
```dockerfile
FROM scratch
COPY main.wasm /main.wasm
EXPOSE 80
ENTRYPOINT [ "main.wasm" ]
```

build image command
```bash
docker buildx build --platform wasi/wasm32 -t go-http .
```

if you get an error uninstall docker and reinstall preview version from  [documentation](https://docs.docker.com/desktop/wasm/)

run container command
```bash
docker run -dp 80:80 --name=go-http --runtime=io.containerd.wasmedge.v1 --platform=wasi/wasm32 go-http
```

**Comment by nlepage** [comment]
Hi @mjcc30 
This project is not intended to run an actual HTTP server, but rather emulate one in a browser's service worker.
In other words, this project doesn't target WASI, but browsers WASM.
Hope this answers your question.
